# Generated by Django 5.0.4 on 2024-04-26 04:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_module_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='finishers',
            field=models.ManyToManyField(blank=True, null=True, related_name='module_finishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='module',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='module_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
