# Generated by Django 5.0.4 on 2024-04-26 04:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_module_finishers_alter_module_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='finishers',
            field=models.ManyToManyField(blank=True, null=True, related_name='lesson_finishers', to=settings.AUTH_USER_MODEL),
        ),
    ]
