# Generated by Django 5.0.4 on 2024-04-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_module_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
