# Generated by Django 5.0.4 on 2024-04-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lesson_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='resource',
            field=models.FileField(null=True, upload_to='files/lessons/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
