# Generated by Django 5.0.4 on 2024-04-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_lesson_resource_alter_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='resource',
            field=models.FileField(blank=True, null=True, upload_to='files/lessons/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
