# Generated by Django 5.0.4 on 2024-04-28 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_lesson_resource_alter_lesson_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='feedbackers',
            field=models.ManyToManyField(blank=True, null=True, related_name='course_feedbackers', to=settings.AUTH_USER_MODEL),
        ),
    ]
